### ISSUE TITLE
Saving resources and new resource generation

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#1]
It is not clear on how to save changes to the notebook. 
Use case 1: user opens someone elses ipynb and makes changes and want to save the changes as a new ipynb
Use case 2: user opens their own ipynb and wants to save changes WITHOUT making a new ipynb

What are the workflow steps from the launch page?
C

**Comment by ChristinaB** [comment]
Hi Tony, I think we got closer on this but is this the final version of how we want to do it? LMK if I should close this issue.

**Comment by Castronova** [comment]
Resource creation and notebook archiving has been documented in the welcome.ipynb page.  Closing for now, we can reopen later if necessary.
