### ISSUE TITLE
Plan for managing libraries loaded on servers

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#19]
@Castronova and @ddcamiu  
I have shared this feature with you, 
https://www.hydroshare.org/resource/e1b40ea6f409447c804abf78ab12d1cf/
If you launch this from the HydroShare browser, and run, you will get a range of errors, most I think have to do with importing from libraries not installed yet on servers.  

What is your preference for requesting installations? 
For Geohackweek and other applications, running Google Earth Engine will be important, for example, but other modules, like xarray, that limits the shared resource of above.   

Here is the error I get: 

ImportErrorTraceback (most recent call last)
<ipython-input-1-7b54fbffe4eb> in <module>()
     15 from scipy import stats
     16 
---> 17 import xarray as xr

ImportError: No module named xarray

**Comment by ChristinaB** [comment]
PS. I get a different set of errors when running this on the USU development and NCSA servers.  I don't quite know how to interpret them. 
From Tony's Dev server;
ERROR: Internal Python error in the inspect module.
Below is the traceback from this internal error.


Unfortunately, your original traceback can not be constructed.

**Comment by Castronova** [comment]
Right now there is no formal way of requesting package/library installation.   For now, please create a new issue and tag it with the **Missing Library** label and I'll include it in the docker build.  

You can also install missing packages into your container by opening a terminal and running a `pip` command, e.g. : 

1. go to Jupyter file directory/explorer
2. New - > Terminal
3. `pip install xarray`

---

> PS. I get a different set of errors when running this on the USU development and NCSA servers. I don't quite know how to interpret them. 

Which line of the notebook is causing this error?

**Comment by ChristinaB** [comment]
Woohoo. That worked. I also needed to install 
Image
Where could I start a list?  Here?
Thanks!

**Comment by ChristinaB** [comment]
Almost there:  
I tried to run this code after  pip install Image
but still get an error when I try to execute: 
from PIL import Image
im = Image.fromarray(A)
im.save("your_file.jpeg")

**Comment by Castronova** [comment]
This is the error that I get.  It looks like `A` is undefined.

```
NameErrorTraceback (most recent call last)
<ipython-input-8-a56eb67d3902> in <module>()
      2 
      3 from PIL import Image
----> 4 im = Image.fromarray(A)
      5 im.save("your_file.jpeg")

NameError: name 'A' is not defined
```
