### ISSUE TITLE
Request to install DHSVM

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#43]
Hi Tony, 
If you git clone  https://github.com/pnnl/DHSVM-PNNL.git   - how do you get just this branch? 
https://github.com/pnnl/DHSVM-PNNL/tree/glacier/DHSVM

How I install it is 
	• Run Makefile in Lib/ directory
		○ %cd Lib 
		○ remove existing libcxsparse.a 
		○ run % make  
			§ This will create the libcxsparse.a file required to compile the main source code
	• Run Makefile in /sourcecode directory 
		○ % cd ../sourcecode
		○ Edit make file so it will run without the netcdf code
			Line 34, "DEFS=…"   remove -DHAVE_NETCDF
			Line 51, "LIBS=…"   remove -lnetcdf
		○  % make

**Comment by Castronova** [comment]
@ChristinaB Do you have plans to use this model in a workshop?  If not, do you have a notebook that I can test the installation against once completed?

**Comment by Castronova** [comment]
@ChristinaB I have this working on my development environment but I have 2 questions:

1. Why are we using the `glacier` branch?  I would like to use the main (master) branch if possible. 

2. Do you have a dataset that I can test the installation on?  The `input 3x3` and `input Mercer` are not working.

**Comment by ChristinaB** [comment]
Still working on it! I just need to rename and retry to make a resource.

**Comment by Castronova** [comment]
@ChristinaB DHSVM3.1.3 is running on jupyter.uwrl.usu.edu.

```
!DHSVM3.1.3
```

**Comment by ChristinaB** [comment]
I finally got DHSVM running on HydroShare !!! Yeah!! Thanks Tony. It works as expected (which is wonderful).
