### ISSUE TITLE
Request to install ULMO

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#44]
Ulmo has had recent developments to add tools for accessing CUAHSI Water One Flow
https://ulmo.readthedocs.io/en/latest/api.html#module-ulmo.cuahsi.his_central
This would be great to have installed, so we can use Notebooks to access the HIS.  

When we tested these on our local terminal, we had to do pip install after conda install didn't work (or maybe both were necessary? )

These are the awesome functions for the observatory utilities

ulmo.cuahsi.wof.get_sites(wsdl_url, suds_cache=('default', ))
ulmo.cuahsi.wof.get_site_info(wsdl_url, site_code, suds_cache=('default', ))
ulmo.cuahsi.wof.get_values(wsdl_url, site_code, variable_code, start=None, end=None, suds_cache=('default', ))
ulmo.cuahsi.wof.get_variable_info(wsdl_url, variable_code=None, suds_cache=('default', ))

**Comment by ChristinaB** [comment]
Governance Notes
[Link to ongoing Discussion ](https://docs.google.com/document/d/1g1Z9jO-Q0HHg43MbngyN3N7m0nK9CC9HXW0EvpRqgQg/edit#)  

Web page draft for Governance developed in Google Docs
 [Link to Draft Governance webpage](https://docs.google.com/document/d/17MAIpCNzojmoPCSD8lLYyVcSZ0g9G_iKZkTCi65PqyI/edit)

**Comment by Castronova** [comment]
@ChristinaB I think this is a good place to put library requests.  Keeping each in a separate issue will help us keep track of which libraries have (and have not) been installed.  I created a label to help us sort these installation requests.

**Comment by ChristinaB** [comment]
Hi Tony, 
Does the In Beta tag above mean I should test it and close this issue? 
Thanks!
Also, Katy Barnhart wants to use the server for a CSDMS Landlab workshop and wanted to jump in on requesting an install.   It seems like the process could result in a 'How to' request an install on the help pages.  What do you think? 
C

**Comment by Castronova** [comment]
@ChristinaB I'm using the Beta tag to indicate issues that have been deployed to the USU beta server.  This installation has been addressed, but unfortunately the beta server is down right now. 

Creating and issue and tagging it as "Install Request" is the best way to request a library install.  Send me an email too since I'm guessing that this needs to be done right away.

**Comment by ChristinaB** [comment]
I don't know about 'right away', Katy and I want to test using Dakota, a National Labs package for optimization, and she wanted to post that request.   I think if there is a regular schedule posted, folks would be able to plan around it.  or if you and @ddcamiu think that you can get an installation done within 5 business days after a request is made, you could post that somewhere.  

What tag will you use @ddcamiu ? That way the requester knows when things are installed. Thanks!

**Comment by Castronova** [comment]
merged into master: 7df7d1c6d428ca8993b739b3eac89109d083ed0c
