### ISSUE TITLE
I ran out of disk space on NCSA- what do I do?

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#45]
I am such a lazy space manager.  I have no idea what the size of the data I downloaded is, or how much I am allotted.      I went to the HELP pages, and there are no details there, so I guess we need to add a bit on limitations on https://pages.hydroshare.org/modeling/jupyter-python-notebook/
I think what I really need is code to remove data files from the server once I have put them on HydroShare.
Stuck,
Christina

**Comment by Castronova** [comment]
@ChristinaB I need to implement some tools to help users clean there userspace.  I'm not sure how much space you've been given on NCSA but I can look into it, or you can ask them directly via help+roger@ncsa.illinois.edu.  

The easiest way to clean up space is to first open up a new notebook terminal, move into the directory you where your data is (e.g. `cd notebooks/data)`. 

### List the size of the directory

```
$ du -sh
```

### Remove a directory (recursively).  Warning: this action is permanent

```
$ rm -rf ./7a71159cf3334fc6a2fde6ca5666b458
```

**Comment by ddcamiu** [comment]
Just came across this issue and did some quick check for help: the total volume assigned for the hydro Jupyter server is 100GB. Right now I see the space is mostly occupied. Most users take on a reasonable portion (~ 1GB), but user "llenoard" has taken 34GB on his own. Inferring from the folder names, I guess he has been constantly versioning his 3GB workflow for about 10 times by making copies. 

Depending on the designed usage purposes, there could be multiple solutions to resolve the storage issue. Should any help needed from NCSA's side, please feel free to contact help+roger@ncsa.illinois.edu.

**Comment by ChristinaB** [comment]
Thanks for that information! Is there any limit on individual users?  Or is the HydroShare total currently managed between users in an adhoc fashion? 
Currently, I think it's just UW and llenorard working on it, but this will eventually become a bigger issue.

**Comment by Castronova** [comment]
Modified the native jupyterhub delete functionality to support recursive folder deletion.  7df7d1c6d428ca8993b739b3eac89109d083ed0c
