### ISSUE TITLE
Welcome Page on USU Beta - get error

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#48]
@Castronova 
I used the USU Beta server to open two different pubilc resources and get the same error.  Looks like you are using Get? so is this for public resources only?

Here is the error I get when I test with 
Public and shareable resource that I do not own (I have edit/author permissions: https://www.hydroshare.org/resource/1de72928f573433290f6c8bb393523df/

Public and shareable resource that I do own
https://www.hydroshare.org/resource/0183ec4000f644fa9378cf28cfe5c2e2/

Same error for both:
![image](https://cloud.githubusercontent.com/assets/4108369/24974263/7a13d73a-1f76-11e7-8908-2206cf0068bc.png)

**Comment by Castronova** [comment]
@ChristinaB This seems to be an issue with the `hs_restclient`.  Please post this issue the rest client project: https://github.com/hydroshare/hs_restclient

To reproduce the error:

*HydroShare Resource Info*
- Public
- Shareable
- Not owned by tester

```
>>> from hs_restclient import HydroShare, HydroShareAuthBasic
>>> username ="my-user-name"
>>> password="my-password"
>>> auth = HydroShareAuthBasic(username=username, password=password)
>>> hs = HydroShare(auth=auth)
>>> hs.getResource('1de72928f573433290f6c8bb393523df', destination='.', unzip=True)
...
...
...
HydroShareHTTPException: Received status 500 Internal Server Error when accessing 
https://www.hydroshare.org/hsapi/resource/1de72928f573433290f6c8bb393523df/ 
with method GET and params None.
```

```
>>> import hs_restclient
>>> print(hs_restclient.__version__)
'1.2.6'
```

**Comment by ChristinaB** [comment]
Thanks! I moved it over there. Do you want me to close this? Or you can. 

Did you switch to wget?
