### ISSUE TITLE
Issue about Issues that we have Issues

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#50]
Hi @Castronova 
I'm just following up with our conversation where you mentioned that you would be tagging, closing and communicating on these issues.  When I google JupyterHub NCSA (because i was searching for a citation) - all I see is our pile of issues!  So we need to either close them and clean them up, or start adding issues about how wonderful it is working!! and how wonderful it is to be actively changing the culture of how science is shared!
C

**Comment by Castronova** [comment]
Not sure what to do about this since this is where all issues relating to the HydroShare JupyterHub software should be placed.  I don't think we can (or want) to omit these from google searches.  I will continue to try an keep the list of issues clean and up-to-date.
