### ISSUE TITLE
Code check on addContentToExistingResource(parent_resource, files)

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#55]
![image](https://cloud.githubusercontent.com/assets/4108369/26078385/3fcbfd1a-3974-11e7-8d75-1445168acf9a.png)

If you open this resource, you can see the saved results and the error printed above.  

https://www.hydroshare.org/resource/fb02f0618ef14a0ba52b7a67fc3cef60/

Can you let me know if we are using Option B code correctly for saving to an existing resource? I looked in utilities/HydroShare/hydroshare.py but there wasn't enough documentation for me to be able to figure out if I was coding it wrong.  This code has operated in the past.  

Notice that it says it saved the files successfully, but it does not, and gives the error. 

Thanks!

**Comment by Castronova** [comment]
Old.  Reopen if this is encountered again.
