### ISSUE TITLE
Unexpected HS_RES_ID on welcome page

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#56]
@Castronova 
I went to HS resource: https://www.hydroshare.org/resource/95f464e3848447858d09e78b8aa3ea2e/
Open With
NSCA
and executed the first cell in the new welcome page and got this output pointing to the wrong ID: 
![image](https://cloud.githubusercontent.com/assets/4108369/26173111/8899450c-3aff-11e7-8356-7194d4123bf0.png)

I tried restarting the kernal.  I closed all running notebooks and terminals, retried the cell, and got the same results.  I went to control Panel, stopped the server, restarted, and got the same result.  I was working with the 07a4ed3b9a984a2fa98901dcb6751954 resource yesterday, but can not see how to clear it from this welcome page pointing towards it...

I think that understanding this issue will help clear up initial steps like @dtarb did to clear the server to be sure it opened the correct resource.  Thanks!!

**Comment by Castronova** [comment]
@ChristinaB @dtarb I am having trouble replicating this error and can't find anything in the logs that pinpoints a specific bug.  This may be something we need to debug over a telecon.  However, I'll keep debugging this issue, but can you run the following commands in the Jupyter terminal and paste the output?

1. `ls -la ~/work/notebooks/.env`

2. `ls -la ~/work/notebooks/utilities` 

3. `cat ~/work/notebooks/.env`

4. `cat ~/work/notebooks/utilities/env`

**Comment by ChristinaB** [comment]
Tony, I don't know why, but today when I tried, it downloaded the correct resource.  I can't recreate this bug today, but let's keep this open, and when it happens again, I will paste the outputs from the commands above.

**Comment by Castronova** [comment]
It seems that this happens when JupyterHub not launched from HydroShare.  The cached HydroShare resource is reloaded since no other resource was specified.
