### ISSUE TITLE
Request to install R

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#57]
Hi Tony, 
I've had two users ask me about R on HydroShare so am passing along this installation request from them.  
I think you mentioned this before, but we do have mounting evidence that a lot of people would find this very useful.
Christina

**Comment by Castronova** [comment]
@ChristinaB Do you have an R workflow that I can use to develop this functionality?

**Comment by Castronova** [comment]
<img width="1179" alt="screen shot 2017-09-17 at 10 12 54 am" src="https://user-images.githubusercontent.com/4822372/30522127-d796b94a-9b90-11e7-9e70-2c01aef28ca1.png">
