### ISSUE TITLE
500: Internal Server Error - notebooks not launching Welcome page on NCSA

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#59]
@ddcamiu and @Castronova 
I was checking the Notebooks in this Collection resource (https://www.hydroshare.org/resource/2610b5c20e9049b4b6d8c11505d931b5/) for this weeks conference and got this error.  They do work from Beta (which I have access to), but the CSDMS conference is planning to launch from NCSA.   

![image](https://cloud.githubusercontent.com/assets/4108369/26369630/16cf4494-3faa-11e7-93cf-1c1beff6ead5.png)

**Comment by Castronova** [comment]
@christina can you start your jupyterhub server at all?

**Comment by ChristinaB** [comment]
OK, I just started it on a different machine without a problem.    
Any idea how this error happens and how to avoid it? 

I get it from my desktop, but not from my laptop. Good news is that CSDMS have not reported this issue either.

**Comment by Castronova** [comment]
@ChristinaB I think this was caused by me updating the docker image (fyi DHSVM3.1.3 is running on NCSA now).  I cleared some jupyterhub cookies and restarted the service.  Looks like that fixed it.

**Comment by ChristinaB** [comment]
Cool!  I have such great timing...

**Comment by ChristinaB** [comment]
Thanks! I'll test DHSVM!
