### ISSUE TITLE
This site can't be reached - Server is down

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#61]
@ddcamiu @Castronova @dtarb 
The jupyter.cuahsi.org  server is down. When will it be working again?. It would be great to have a notification (email, Slack, or even text message?) so that when work plans are derailed because the server is down, users know how to plan and work around. 
Thanks

**Comment by Castronova** [comment]
This is an unplanned outage.   NCSA is having some issues with Open Stack which may have caused JupyterHub to crash.   Dandong is currently working to fix it.

**Comment by ddcamiu** [comment]
Actually I think it should be fixed by now. Have you tried logging in and starting the servive @Castronova? I would like to try, but I am less familiar with the latest version of the hydro-jupyter service management.

**Comment by ChristinaB** [comment]
Thanks !! Standing by to test launch when the server is restarted

**Comment by ddcamiu** [comment]
I tried to start the service based on the history records. I think it now works for me at least.

**Comment by ChristinaB** [comment]
![image](https://user-images.githubusercontent.com/4108369/27250040-2be3eee2-52d9-11e7-913f-8e5af9ad6ce2.png)

This is the error I get when I tried.

**Comment by Castronova** [comment]
I just cleaned the cached jupyterhub files and it works for me now.  @ChristinaB let me know if it's working for you now.
