### ISSUE TITLE
Request to install geopandas

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#65]
conda install geopandas
pip install geopandas

I am using this for the 'Lowering the barriers' paper and will share that resource so you can check out the use case notebooks asap.  

Question: I installed this from terminal yesterday, but I had to reinstall it today.  Does the personal user space get cleared for software installs? I didn't think it did...

**Comment by Castronova** [comment]
@ChristinaB can you test this on http://jupyter.uwrl.usu.edu/
