### ISSUE TITLE
ImportError: cannot import name TimeSeries (rhessys)

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare-jupyterhub#89]
When attempting:

`from utilities.rhessys import *`

I get the following error (w/ traceback)

ImportErrorTraceback (most recent call last)
<ipython-input-1-60d71dd97f3d> in <module>()
      1 import os
      2 import logging
----> 3 from utilities.rhessys import *
      4 get_ipython().magic(u'matplotlib inline')

/home/jovyan/work/notebooks/utilities/rhessys.py in <module>()
     18 import numpy as np
     19 import pandas as pd
---> 20 import statsmodels.api as sm
     21 import matplotlib.pyplot as plt
     22 import matplotlib

/opt/conda/envs/python2/lib/python2.7/site-packages/statsmodels/api.py in <module>()
      3 from . import tools
      4 from .tools.tools import add_constant, categorical
----> 5 from . import regression
      6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
      7 from .regression.quantile_regression import QuantReg

/opt/conda/envs/python2/lib/python2.7/site-packages/statsmodels/regression/__init__.py in <module>()
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels import NoseWrapper as Tester
      4 test = Tester().test

/opt/conda/envs/python2/lib/python2.7/site-packages/statsmodels/regression/linear_model.py in <module>()
     50                                           cache_readonly,
     51                                           cache_writable)
---> 52 import statsmodels.base.model as base
     53 import statsmodels.base.wrapper as wrap
     54 from statsmodels.emplike.elregress import _ELRegOpts

/opt/conda/envs/python2/lib/python2.7/site-packages/statsmodels/base/model.py in <module>()
      3 import numpy as np
      4 from scipy import stats
----> 5 from statsmodels.base.data import handle_data
      6 from statsmodels.tools.tools import recipr, nan_dot
      7 from statsmodels.stats.contrast import ContrastResults

/opt/conda/envs/python2/lib/python2.7/site-packages/statsmodels/base/data.py in <module>()
      6 from statsmodels.compat.numpy import np_matrix_rank
      7 import numpy as np
----> 8 from pandas import DataFrame, Series, TimeSeries, isnull
      9 from statsmodels.tools.decorators import (resettable_cache, cache_readonly,
     10                                           cache_writable)

ImportError: cannot import name TimeSeries

**Comment by Castronova** [comment]
resolved in #95
