### ISSUE TITLE
GDAL libraries not importing 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare-jupyterhub#97]
Do the following
1. Open JupyterHub NCSA from any HydroShare Resource
2. From the welcome notebook open the first example notebook "Raster Processing using TauDEM"
3. Execute the first computable cell in this notebook 

The line
> from utilities import hydroshare, taudem

fails due to a GDAL library problem.

I believe this may be due to an update to the Anaconda environment that broke this functionality.

**Comment by Castronova** [comment]
resolved in #95
