### ISSUE TITLE
Install Sciunit client to support Geotrust work

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare-jupyterhub#98]
Install most recent sciunit client from https://bitbucket.org/geotrust/sciunit2 to support geotrust reproducible workflow Earthcube collaborative project with Tanu Malik and @goodalljl 

@lichray could help with details if needed.

**Comment by lichray** [comment]
Here is the pull request I made https://github.com/hydroshare/hydroshare-jupyterhub/pull/78

**Comment by dtarb** [comment]
@lichray thanks!

**Comment by Castronova** [comment]
@lichray I'm working to get you PR merged this week.

**Comment by Castronova** [comment]
resolved in #105
